const navigationItemProps = [
    {
        key: 'PERFORMANCE',
        title: 'Performance',
        type: 'group',
        style: navigationItemStyles.outcome,
        soundURL: 'sounds/universe-loop-1.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .075,
        pathSpeed: .0003,
        pathOffset: 0,
        subItems: [
            'LIFE CAMPUS TOP LEVEL',
            'EARLIER ITERATIONS',
        ]
    },
    {
        key: 'LIFE CAMPUS TOP LEVEL',
        title: 'LIFE Campus Performance',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .075,
        pathSpeed: .0003,
        pathOffset: 0,
    },
    {
        key: 'EARLIER ITERATIONS',
        title: 'Earlier Iterations',
        type: 'subGroup',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .075,
        pathSpeed: .0003,
        pathOffset: Math.PI,
        subItems: [
            'WHAT SOUNDS DO',
            'THE LOBBY',
            'IMMERSIVE CONCERT SERIES',
            `WHAT'S NEXT`,
            'SOUND & SCIENCE',
            'VEGA LAB',
            'HOW TO STUDY SOUND',
            '3DAYSOFDESIGN',
            'VOICE STUDIES',
            'VOCAL IMAGINARIES',
            'SPATIAL SOUND MEETUP',
            'DKDM',
            'AMBISONIC NIGHTS #7'
        ],
    },
    {
        key: 'SPATIAL SCORES',
        title: 'Spatial Scores',
        type: 'group',
        style: navigationItemStyles.outcome,
        soundURL: 'sounds/universe-loop-2.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .075,
        pathSpeed: .0003,
        pathOffset: Math.PI,
        subItems: [
            'GHOSTLY VOICES',
            'AT FIRST',
        ]
    },
    {
        key: 'GHOSTLY VOICES',
        title: 'Ghostly Voices',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619220',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .075,
        pathSpeed: .0003,
        pathOffset: 0,
    },
    {
        key: 'AT FIRST',
        title: 'At First',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619242',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .075,
        pathSpeed: .0003,
        pathOffset: Math.PI,
    },
    {
        key: 'MULTI VOICING SPATIAL SONGS',
        title: 'Multi—Voicing Spatial Songs',
        type: 'group',
        style: navigationItemStyles.outcome,
        soundURL: 'sounds/universe-loop-5.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .24,
        pathSpeed: .00009,
        pathOffset: 0,
        subItems: [
            'About the Anthology',
            'SØSTR',
            'DU—o',
            'Jo Verwohlt',
            'Lil Lacy',
            'Philip | Schneider',
            'Quiver',
            'Sitrekin',
            'Sofie Birch',
            'SØS Gunver Ryberg',
            'SØSTR',
            'XYZ Sound Collective',
            'Yann Coppier']
    },
    {
        key: 'About the Anthology',
        title: 'About the Anthology',
        type: 'subItem',
        link: 'https://media.researchcatalogue.net/rc/master/20/b4/ed/03/20b4ed03c78cd7b279e9f64e608b0171.pdf?t=39503e2b819c9a4f56a97bd340ae5bda&e=1747083300',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .02,
        pathSpeed: .0003,
        pathOffset: 0,
    },
    {
        key: 'DU—o',
        title: 'DU—o',
        type: 'subItem',
        link: 'https://media.researchcatalogue.net/rc/master/7d/9b/c1/0a/7d9bc10a5b9d7262b1535198d9358ca8.pdf?t=f8e99f40261d2bd7d5ab37138edf9e7c&e=1747083300',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .1,
        pathSpeed: .0002,
        pathOffset: Math.PI,
    },
    {
        key: 'Jo Verwohlt',
        title: 'Jo Verwohlt',
        type: 'subItem',
        link: 'https://media.researchcatalogue.net/rc/master/0d/52/52/03/0d525203f52d30d387c73114977084cb.pdf?t=66f1dccef6daff18732c9c3859a69e37&e=1747083300',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .2,
        pathSpeed: .0001,
        pathOffset: 0,
    },
    {
        key: 'Lil Lacy',
        title: 'Lil Lacy',
        type: 'subItem',
        link: 'https://media.researchcatalogue.net/rc/master/cc/dc/29/31/ccdc2931b6c3e88be35a45fba06c20d3.pdf?t=58fddff0959c9f922cd4e0fb0d67fb0f&e=1747083300',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .2,
        pathSpeed: .0001,
        pathOffset: 2 * Math.PI / 3,
    },
    {
        key: 'Philip | Schneider',
        title: 'Philip | Schneider',
        type: 'subItem',
        link: 'https://media.researchcatalogue.net/rc/master/38/d0/57/b5/38d057b54b6860cce05376d738d3cfc2.pdf?t=e415ccd1b621e00e05b9dac973f50be0&e=1747083300',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .2,
        pathSpeed: .0001,
        pathOffset: 4 * Math.PI / 3,
    },
    {
        key: 'Quiver',
        title: 'Quiver',
        type: 'subItem',
        link: 'https://media.researchcatalogue.net/rc/master/ed/90/a8/80/ed90a88012b0d47e09ce470dea3275db.pdf?t=6c29737e938de191fe97db406adbf800&e=1747083300',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .3,
        pathSpeed: .00005,
        pathOffset: 0,
    },
    {
        key: 'Sitrekin',
        title: 'Sitrekin',
        type: 'subItem',
        link: 'https://media.researchcatalogue.net/rc/master/aa/27/b8/9f/aa27b89f4494a0006da69e5a9e81470e.pdf?t=a7f38d76984b826bac4549d971112275&e=1747083300',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .3,
        pathSpeed: .00005,
        pathOffset: Math.PI / 3,
    },
    {
        key: 'Sofie Birch',
        title: 'Sofie Birch',
        type: 'subItem',
        link: 'https://media.researchcatalogue.net/rc/master/f0/91/3f/9f/f0913f9f8123b2d4e4022ca6bb285d14.pdf?t=9804e9b867652affec1a80be1a354724&e=1747083300',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .3,
        pathSpeed: .00005,
        pathOffset: 2 * Math.PI / 3,
    },
    {
        key: 'SØS Gunver Ryberg',
        title: 'SØS Gunver Ryberg',
        type: 'subItem',
        link: 'https://media.researchcatalogue.net/rc/master/44/bd/2b/d2/44bd2bd2cb7bdd46d6fb080e70dd16de.pdf?t=9b51a6c699e3a6482068843b05302ffc&e=1747083300',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .3,
        pathSpeed: .00005,
        pathOffset: 3 * Math.PI / 3,
    },
    {
        key: 'SØSTR',
        title: 'SØSTR',
        type: 'subItem',
        link: 'https://media.researchcatalogue.net/rc/master/1d/7d/74/32/1d7d743241c14c64f18617f33e4aa30e.pdf?t=5eea2bed6338bb2a1a5a3b228b236b4b&e=1747083300',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .1,
        pathSpeed: .0002,
        pathOffset: 0,
    },
    {
        key: 'XYZ Sound Collective',
        title: 'XYZ Sound Collective',
        type: 'subItem',
        link: 'https://media.researchcatalogue.net/rc/master/2a/27/d4/8d/2a27d48df46a5daa02d460cc5b59d32a.pdf?t=139453a766bfd64e0dc12174f7c286e0&e=1747083300',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .3,
        pathSpeed: .00005,
        pathOffset: 4 * Math.PI / 3,
    },
    {
        key: 'Yann Coppier',
        title: 'Yann Coppier',
        type: 'subItem',
        link: 'https://media.researchcatalogue.net/rc/master/78/ac/f0/26/78acf026e3e00043f53c2a8ad2ba2f1b.pdf?t=960b5520061d98e435d7b86865cbc7fb&e=1747083300',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .3,
        pathSpeed: .00005,
        pathOffset: 5 * Math.PI / 3,
    },
    {
        key: 'SPATIAL STRATEGIES',
        title: 'Spatial Strategies',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3539951',
        style: navigationItemStyles.outcome,
        soundURL: 'sounds/universe-loop-6.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .24,
        pathSpeed: .00009,
        pathOffset: 2 * Math.PI / 3,
    },
    {
        key: 'INTERFACES',
        title: 'Interfaces',
        type: 'group',
        style: navigationItemStyles.outcome,
        soundURL: 'sounds/universe-loop-7.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .24,
        pathSpeed: .00009,
        pathOffset: 4 * Math.PI / 3,
        subItems: ['CHAOS PENDULUM INTERFACE OVERVIEW', `SPACE HALO (HALO D'ESPACE) INTERFACE OVERVIEW`, 'BAGUA INTERFACE INTERFACE OVERVIEW']
    },
    {
        key: 'CHAOS PENDULUM INTERFACE OVERVIEW',
        title: 'Chaos Pendulum',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3539328',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .125,
        pathSpeed: .0001,
        pathOffset: 0,
    },
    {
        key: `SPACE HALO (HALO D'ESPACE) INTERFACE OVERVIEW`,
        title: `Space Halo \n(Halo d'Espace)`,
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3539325',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .125,
        pathSpeed: .0001,
        pathOffset: Math.PI * 2 / 3,
    },
    {
        key: 'BAGUA INTERFACE INTERFACE OVERVIEW',
        title: 'Bagua',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3539322',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .125,
        pathSpeed: .0001,
        pathOffset: Math.PI * 4 / 3,
    },
    {
        key: 'SONGWRITING',
        title: 'Songwriting',
        type: 'group',
        style: navigationItemStyles.process,
        soundURL: 'sounds/universe-loop-4.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .5,
        pathSpeed: .00007,
        pathOffset: 0,
        subItems: ['GHOSTLY VOICES SONGWRITING', 'SWEET SPOT EXPERIMENT SONGWRITING', '12 BUTTERFLIES SONGWRITING']
    },
    {
        key: 'GHOSTLY VOICES SONGWRITING',
        title: 'Ghostly Voices',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619401',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 0,
    },
    {
        key: 'SWEET SPOT EXPERIMENT SONGWRITING',
        title: 'Sweet Spot',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619394',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 3 * Math.PI / 5,
    },
    {
        key: '12 BUTTERFLIES SONGWRITING',
        title: '12 Butterflies',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619397',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 6 * Math.PI / 5,
    },
    {
        key: 'GOING SPATIAL',
        title: 'Going Spatial',
        type: 'group',
        style: navigationItemStyles.process,
        soundURL: 'sounds/universe-loop-8.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .5,
        pathSpeed: .00007,
        pathOffset: Math.PI / 3,
        subItems: ['FROM STEREO TO SPATIAL', 'EVENTS', 'INTERFACE DESIGN']
    },
    {
        key: 'FROM STEREO TO SPATIAL',
        title: 'From Stereo to Spatial',
        type: 'subGroup',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 0,
        subItems: ['NOTATION', 'STRUCTURE ARRANGEMENT', 'VOCAL APPROACH', 'INSTRUMENTATION'],
    },
    {
        key: 'NOTATION',
        title: 'Notation',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619472',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 0,
    },
    {
        key: 'STRUCTURE ARRANGEMENT',
        title: 'Structure \nArrangement',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619476',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 3 * Math.PI / 5,
    },
    {
        key: 'VOCAL APPROACH',
        title: 'Vocal Approach',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619480',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 6 * Math.PI / 5,
    },
    {
        key: 'INSTRUMENTATION',
        title: 'Instrumentation',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619484',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 9 * Math.PI / 5,
    },

    {
        key: 'EVENTS',
        title: 'Events',
        type: 'subGroup',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 3 * Math.PI / 5,
        subItems: [
            'LIFE CAMPUS',
            'WHAT SOUNDS DO',
            'THE LOBBY',
            'IMMERSIVE CONCERT SERIES',
            `WHAT'S NEXT`,
            'SOUND & SCIENCE',
            'VEGA LAB',
            'HOW TO STUDY SOUND',
            '3DAYSOFDESIGN',
            'VOICE STUDIES',
            'VOCAL IMAGINARIES',
            'SPATIAL SOUND MEETUP',
            'DKDM',
            'AMBISONIC NIGHTS #7'
        ],
    },
    {
        key: 'LIFE CAMPUS',
        title: 'LIFE Campus',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .02,
        pathSpeed: .0003,
        pathOffset: 0,
    },

    {
        key: 'WHAT SOUNDS DO',
        title: 'WHAT SOUNDS DO',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .1,
        pathSpeed: .0001,
        pathOffset: 0,
    },
    {
        key: 'THE LOBBY',
        title: 'The Lobby',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .1,
        pathSpeed: .0001,
        pathOffset: 2 * Math.PI / 3,
    },
    {
        key: 'IMMERSIVE CONCERT SERIES',
        title: 'Immersive Concert Series',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .1,
        pathSpeed: .0001,
        pathOffset: 4 * Math.PI / 3,
    },


    {
        key: `WHAT'S NEXT`,
        title: `What's Next`,
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .22,
        pathSpeed: .00003,
        pathOffset: 0,
    },
    {
        key: 'SOUND & SCIENCE',
        title: 'Sound & Science',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .22,
        pathSpeed: .00003,
        pathOffset: 2 * Math.PI / 5,
    },
    {
        key: 'VEGA LAB',
        title: 'Vega Lab',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.intro,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .22,
        pathSpeed: .00003,
        pathOffset: 4 * Math.PI / 5,
    },
    {
        key: 'HOW TO STUDY SOUND',
        title: 'How to Study Sound',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .22,
        pathSpeed: .00003,
        pathOffset: 6 * Math.PI / 5,
    },
    {
        key: '3DAYSOFDESIGN',
        title: '3daysofdesign',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .22,
        pathSpeed: .00003,
        pathOffset: 8 * Math.PI / 5,
    },

    {
        key: 'VOICE STUDIES',
        title: 'Voice Studies',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .35,
        pathSpeed: .00003,
        pathOffset: 0,
    },
    {
        key: 'VOCAL IMAGINARIES',
        title: 'Vocal Imaginaries',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .35,
        pathSpeed: .00003,
        pathOffset: 2 * Math.PI / 5,
    },
    {
        key: 'SPATIAL SOUND MEETUP',
        title: 'Spatial Sound Meetup',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .35,
        pathSpeed: .00002,
        pathOffset: 4 * Math.PI / 5,
    },
    {
        key: 'DKDM',
        title: 'DKDM',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.thought,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .35,
        pathSpeed: .00002,
        pathOffset: 6 * Math.PI / 5,
    },
    {
        key: 'AMBISONIC NIGHTS #7',
        title: 'Ambisonic Nights #7',
        link: 'https://www.researchcatalogue.net/view/3512750/3619188',
        type: 'subItem',
        style: navigationItemStyles.thought,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .35,
        pathSpeed: .00002,
        pathOffset: 8 * Math.PI / 5,
    },

    {
        key: 'INTERFACE DESIGN',
        title: 'Interface Design',
        type: 'subGroup',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 6 * Math.PI / 5,
        subItems: ['BAGUA DESIGN',
            'SPACE HALO DESIGN',
            'CHAOS PENDULUM DESIGN'],
    },
    {
        key: 'BAGUA DESIGN',
        title: 'Bagua',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619449',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 0,
    },
    {
        key: 'SPACE HALO DESIGN',
        title: `Space Halo \n(Halo d'Espace)`,
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619464',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 3 * Math.PI / 5,
    },
    {
        key: 'CHAOS PENDULUM DESIGN',
        title: 'Chaos Pendulum',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619468',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 6 * Math.PI / 5,
    },


    {
        key: 'VOICE BODY',
        title: 'Voice / Body',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512961',
        style: navigationItemStyles.thought,
        soundURL: 'sounds/universe-loop-3.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .4,
        pathSpeed: .00005,
        pathOffset: 0,
    },
    {
        key: 'FEMINIST EARS THOUGHT',
        title: 'Feminist Ears',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512964',
        style: navigationItemStyles.thought,
        soundURL: 'sounds/universe-loop-9.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .4,
        pathSpeed: .00005,
        pathOffset: 2 * Math.PI / 3,
    },
    {
        key: 'SWEET SPOT THOUGHT',
        title: 'Sweet Spot',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512971',
        style: navigationItemStyles.thought,
        soundURL: 'sounds/universe-loop-10.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .4,
        pathSpeed: .00005,
        pathOffset: 4 * Math.PI / 3,
    },
    {
        key: 'INTRO',
        title: 'Intro',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512978',
        style: navigationItemStyles.intro,
        soundURL: 'sounds/universe-loop-11.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .5,
        pathSpeed: .00012,
        pathOffset: 4 * Math.PI / 3,
    }
]