const navigationItemProps = [
    {
        key: 'performances',
        title: 'Performances',
        type: 'group',
        style: navigationItemStyles.outcome,
        soundURL: 'sounds/universe-loop-1.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .075,
        pathSpeed: .0003,
        pathOffset: 0,
        subItems: [
            'LIFE CAMPUS',
            'WHAT SOUNDS DO',
            'THE LOBBY',
            'IMMERSIVE CONCERT SERIES',
            'IMMERSIVE SOUND SYMPOSIUM',
            'IMMERSIVE AUDIO LAB',
            `WHAT'S NEXT`,
            'SOUND & SCIENCE',
            'VEGA LAB',
            'HOW TO STUDY SOUND',
            '3DAYSOFDESIGN',
            'VOICE STUDIES',
            'VOCAL IMAGINARIES',
            'SPATIAL SOUND MEETUP',
            'DKDM',
            'AMBISONIC NIGHTS #7'
        ],
    },

    // Performances
    {
        key: 'LIFE CAMPUS',
        title: 'LIFE Campus',
        link: 'https://www.researchcatalogue.net/view/3512750/3786663',
        type: 'subItem',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .02,
        pathSpeed: .0003,
        pathOffset: 0,
    },

    {
        key: 'WHAT SOUNDS DO',
        title: 'What Sounds Do',
        link: 'https://www.researchcatalogue.net/view/3512750/3786648',
        type: 'subItem',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .1,
        pathSpeed: .0001,
        pathOffset: 0,
    },
    {
        key: 'THE LOBBY',
        title: 'The Lobby',
        link: 'https://www.researchcatalogue.net/view/3512750/3786669',
        type: 'subItem',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .1,
        pathSpeed: .0001,
        pathOffset: 2 * Math.PI / 3,
    },
    {
        key: 'IMMERSIVE CONCERT SERIES',
        title: 'Immersive\nConcert Series',
        link: 'https://www.researchcatalogue.net/view/3512750/3786672',
        type: 'subItem',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .1,
        pathSpeed: .0001,
        pathOffset: 4 * Math.PI / 3,
    },


    {
        key: `WHAT'S NEXT`,
        title: `What's Next`,
        link: 'https://www.researchcatalogue.net/view/3512750/3786654',
        type: 'subItem',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .22,
        pathSpeed: .00003,
        pathOffset: 0,
    },
    {
        key: 'SOUND & SCIENCE',
        title: 'Sound &\nScience',
        link: 'https://www.researchcatalogue.net/view/3512750/3786678',
        type: 'subItem',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .22,
        pathSpeed: .00003,
        pathOffset: 2 * Math.PI / 5,
    },
    {
        key: 'VEGA LAB',
        title: 'VEGA LAB',
        link: 'https://www.researchcatalogue.net/view/3512750/3786684',
        type: 'subItem',
        style: navigationItemStyles.intro,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .22,
        pathSpeed: .00003,
        pathOffset: 4 * Math.PI / 5,
    },
    {
        key: 'HOW TO STUDY SOUND',
        title: 'How to Study\nSound',
        link: 'https://www.researchcatalogue.net/view/3512750/3663467',
        type: 'subItem',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .22,
        pathSpeed: .00003,
        pathOffset: 6 * Math.PI / 5,
    },
    {
        key: '3DAYSOFDESIGN',
        title: '3daysofdesign',
        link: 'https://www.researchcatalogue.net/view/3512750/3786666',
        type: 'subItem',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .22,
        pathSpeed: .00003,
        pathOffset: 8 * Math.PI / 5,
    },

    {
        key: 'VOICE STUDIES',
        title: 'Voice Studies',
        link: 'https://www.researchcatalogue.net/view/3512750/3786651',
        type: 'subItem',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .35,
        pathSpeed: .00002,
        pathOffset: 0,
    },
    {
        key: 'VOCAL IMAGINARIES',
        title: 'Vocal\nImaginaries',
        link: 'https://www.researchcatalogue.net/view/3512750/3786657',
        type: 'subItem',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .35,
        pathSpeed: .00002,
        pathOffset: 2 * Math.PI / 7,
    },
    {
        key: 'SPATIAL SOUND MEETUP',
        title: 'Spatial Sound\nMeetup',
        link: 'https://www.researchcatalogue.net/view/3512750/3786660',
        type: 'subItem',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .35,
        pathSpeed: .00002,
        pathOffset: 4 * Math.PI / 7,
    },
    {
        key: 'DKDM',
        title: 'DKDM',
        link: 'https://www.researchcatalogue.net/view/3512750/3786681',
        type: 'subItem',
        style: navigationItemStyles.thought,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .35,
        pathSpeed: .00002,
        pathOffset: 6 * Math.PI / 7,
    },
    {
        key: 'AMBISONIC NIGHTS #7',
        title: 'Ambisonic\nNights #7',
        link: 'https://www.researchcatalogue.net/view/3512750/3787211',
        type: 'subItem',
        style: navigationItemStyles.thought,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .35,
        pathSpeed: .00002,
        pathOffset: 8 * Math.PI / 7,
    },
    {
        key: 'IMMERSIVE SOUND SYMPOSIUM',
        title: 'Immersive Sound\nSymposium',
        link: 'https://www.researchcatalogue.net/view/3512750/3786675',
        type: 'subItem',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .35,
        pathSpeed: .00002,
        pathOffset: 10 * Math.PI / 7,
    },
    {
        key: 'IMMERSIVE AUDIO LAB',
        title: 'Immersive\nAudio Lab',
        link: 'https://www.researchcatalogue.net/view/3512750/3786687',
        type: 'subItem',
        style: navigationItemStyles.intro,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .35,
        pathSpeed: .00002,
        pathOffset: 12 * Math.PI / 7,
    },


    {
        key: 'SPATIAL SCORES',
        title: 'Spatial Scores',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3619242',
        style: navigationItemStyles.outcome,
        soundURL: 'sounds/universe-loop-2.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .075,
        pathSpeed: .0003,
        pathOffset: Math.PI,
    },

    {
        key: 'multi-voicing-spatial-songs',
        title: 'Multi—Voicing\nSpatial Songs',
        type: 'group',
        style: navigationItemStyles.outcome,
        soundURL: 'sounds/universe-loop-5.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .24,
        pathSpeed: .00009,
        pathOffset: 0,
        subItems: [
            'About the Anthology',
            'SØSTR',
            'DU—o',
            'Jo Verwohlt',
            'Lil Lacy',
            'Philip | Schneider',
            'Quiver',
            'Sitrekin',
            'Sofie Birch',
            'SØS Gunver Ryberg',
            'SØSTR',
            'XYZ Sound Collective',
            'Yann Coppier']
    },
    {
        key: 'About the Anthology',
        title: 'About the\nAnthology',
        type: 'subItem',
        link: 'https://github.com/jasperkatzban/Voicing-Spatial-Songs-Docs/blob/main/content/Multi-Voicing%20Spatial%20Songs%20-%20Digital%20Edition.pdf?raw=true#page=2',
        openLinkInNewWindow: true,
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .02,
        pathSpeed: .0003,
        pathOffset: 0,
    },

    // Anthology Pages
    {
        key: 'DU—o',
        title: 'DU—o',
        type: 'subItem',
        link: 'https://github.com/jasperkatzban/Voicing-Spatial-Songs-Docs/blob/main/content/Multi-Voicing%20Spatial%20Songs%20-%20Digital%20Edition.pdf?raw=true#page=4',
        openLinkInNewWindow: true,
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .1,
        pathSpeed: .0002,
        pathOffset: Math.PI,
    },
    {
        key: 'Jo Verwohlt',
        title: 'Jo Verwohlt',
        type: 'subItem',
        link: 'https://github.com/jasperkatzban/Voicing-Spatial-Songs-Docs/blob/main/content/Multi-Voicing%20Spatial%20Songs%20-%20Digital%20Edition.pdf?raw=true#page=10',
        openLinkInNewWindow: true,
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .2,
        pathSpeed: .0001,
        pathOffset: 0,
    },
    {
        key: 'Lil Lacy',
        title: 'Lil Lacy',
        type: 'subItem',
        link: 'https://github.com/jasperkatzban/Voicing-Spatial-Songs-Docs/blob/main/content/Multi-Voicing%20Spatial%20Songs%20-%20Digital%20Edition.pdf?raw=true#page=14',
        openLinkInNewWindow: true,
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .2,
        pathSpeed: .0001,
        pathOffset: 2 * Math.PI / 3,
    },
    {
        key: 'Philip | Schneider',
        title: 'Philip | Schneider',
        type: 'subItem',
        link: 'https://github.com/jasperkatzban/Voicing-Spatial-Songs-Docs/blob/main/content/Multi-Voicing%20Spatial%20Songs%20-%20Digital%20Edition.pdf?raw=true#page=24',
        openLinkInNewWindow: true,
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .2,
        pathSpeed: .0001,
        pathOffset: 4 * Math.PI / 3,
    },
    {
        key: 'Quiver',
        title: 'Quiver',
        type: 'subItem',
        link: 'https://github.com/jasperkatzban/Voicing-Spatial-Songs-Docs/blob/main/content/Multi-Voicing%20Spatial%20Songs%20-%20Digital%20Edition.pdf?raw=true#page=30',
        openLinkInNewWindow: true,
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .3,
        pathSpeed: .00005,
        pathOffset: 0,
    },
    {
        key: 'Sitrekin',
        title: 'Sitrekin',
        type: 'subItem',
        link: 'https://github.com/jasperkatzban/Voicing-Spatial-Songs-Docs/blob/main/content/Multi-Voicing%20Spatial%20Songs%20-%20Digital%20Edition.pdf?raw=true#page=40',
        openLinkInNewWindow: true,
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .3,
        pathSpeed: .00005,
        pathOffset: Math.PI / 3,
    },
    {
        key: 'Sofie Birch',
        title: 'Sofie Birch',
        type: 'subItem',
        link: 'https://github.com/jasperkatzban/Voicing-Spatial-Songs-Docs/blob/main/content/Multi-Voicing%20Spatial%20Songs%20-%20Digital%20Edition.pdf?raw=true#page=48',
        openLinkInNewWindow: true,
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .3,
        pathSpeed: .00005,
        pathOffset: 2 * Math.PI / 3,
    },
    {
        key: 'SØS Gunver Ryberg',
        title: 'SØS Gunver\nRyberg',
        type: 'subItem',
        link: 'https://github.com/jasperkatzban/Voicing-Spatial-Songs-Docs/blob/main/content/Multi-Voicing%20Spatial%20Songs%20-%20Digital%20Edition.pdf?raw=true#page=56',
        openLinkInNewWindow: true,
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .3,
        pathSpeed: .00005,
        pathOffset: 3 * Math.PI / 3,
    },
    {
        key: 'SØSTR',
        title: 'SØSTR',
        type: 'subItem',
        link: 'https://github.com/jasperkatzban/Voicing-Spatial-Songs-Docs/blob/main/content/Multi-Voicing%20Spatial%20Songs%20-%20Digital%20Edition.pdf?raw=true#page=64',
        openLinkInNewWindow: true,
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .1,
        pathSpeed: .0002,
        pathOffset: 0,
    },
    {
        key: 'XYZ Sound Collective',
        title: 'XYZ Sound\nCollective',
        type: 'subItem',
        link: 'https://github.com/jasperkatzban/Voicing-Spatial-Songs-Docs/blob/main/content/Multi-Voicing%20Spatial%20Songs%20-%20Digital%20Edition.pdf?raw=true#page=74',
        openLinkInNewWindow: true,
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .3,
        pathSpeed: .00005,
        pathOffset: 4 * Math.PI / 3,
    },
    {
        key: 'Yann Coppier',
        title: 'Yann Coppier',
        type: 'subItem',
        link: 'https://github.com/jasperkatzban/Voicing-Spatial-Songs-Docs/blob/main/content/Multi-Voicing%20Spatial%20Songs%20-%20Digital%20Edition.pdf?raw=true#page=82',
        openLinkInNewWindow: true,
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .3,
        pathSpeed: .00005,
        pathOffset: 5 * Math.PI / 3,
    },

    {
        key: 'SPATIAL STRATEGIES',
        title: 'Spatial\nStrategies',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3539951',
        style: navigationItemStyles.outcome,
        soundURL: 'sounds/universe-loop-6.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .24,
        pathSpeed: .00009,
        pathOffset: 2 * Math.PI / 3,
    },
    {
        key: 'interfaces',
        title: 'Interfaces',
        type: 'group',
        style: navigationItemStyles.outcome,
        soundURL: 'sounds/universe-loop-7.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .24,
        pathSpeed: .00009,
        pathOffset: 4 * Math.PI / 3,
        subItems: ['CHAOS PENDULUM INTERFACE OVERVIEW', `SPACE HALO INTERFACE OVERVIEW`, 'BAGUA INTERFACE INTERFACE OVERVIEW']
    },

    // Interfaces (outcomes)
    {
        key: 'CHAOS PENDULUM INTERFACE OVERVIEW',
        title: 'Chaos Pendulum',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619468',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .125,
        pathSpeed: .0001,
        pathOffset: 0,
    },
    {
        key: `SPACE HALO INTERFACE OVERVIEW`,
        title: `Space Halo`,
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619464',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .125,
        pathSpeed: .0001,
        pathOffset: Math.PI * 2 / 3,
    },
    {
        key: 'BAGUA INTERFACE INTERFACE OVERVIEW',
        title: 'Bagua',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619449',
        style: navigationItemStyles.outcome,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .125,
        pathSpeed: .0001,
        pathOffset: Math.PI * 4 / 3,
    },
    {
        key: 'songwriting',
        title: 'Songwriting',
        type: 'group',
        style: navigationItemStyles.process,
        soundURL: 'sounds/universe-loop-4.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .5,
        pathSpeed: .00007,
        pathOffset: 0,
        subItems: ['GHOSTLY VOICES SONGWRITING', 'SWEET SPOT EXPERIMENT SONGWRITING', '12 BUTTERFLIES SONGWRITING']
    },

    // Songwriting
    {
        key: 'GHOSTLY VOICES SONGWRITING',
        title: 'Ghostly Voices',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619401',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 0,
    },
    {
        key: 'SWEET SPOT EXPERIMENT SONGWRITING',
        title: 'Sweet Spot',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619394',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 3 * Math.PI / 5,
    },
    {
        key: '12 BUTTERFLIES SONGWRITING',
        title: 'Hymn for 12 Butterflies',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619397',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 6 * Math.PI / 5,
    },

    // Going Spatial
    {
        key: 'going-spatial',
        title: 'Going Spatial',
        type: 'group',
        style: navigationItemStyles.process,
        soundURL: 'sounds/universe-loop-8.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .5,
        pathSpeed: .00007,
        pathOffset: Math.PI / 3,
        subItems: ['FROM STEREO TO SPATIAL', 'interface-design']
    },
    {
        key: 'FROM STEREO TO SPATIAL',
        title: 'From Stereo to Spatial',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619476',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 0,
    },
    {
        key: 'interface-design',
        title: 'Interface Design',
        type: 'subGroup',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 6 * Math.PI / 5,
        subItems: [
            'BAGUA DESIGN',
            'SPACE HALO DESIGN',
            'CHAOS PENDULUM DESIGN'],
    },

    // Interfaces (Process)
    {
        key: 'BAGUA DESIGN',
        title: 'Bagua',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619449',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 0,
    },
    {
        key: 'SPACE HALO DESIGN',
        title: `Space Halo`,
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619464',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 3 * Math.PI / 5,
    },
    {
        key: 'CHAOS PENDULUM DESIGN',
        title: 'Chaos Pendulum',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3619468',
        style: navigationItemStyles.process,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .3,
        pathSpeed: .0001,
        pathOffset: 6 * Math.PI / 5,
    },



    // Thoughts
    {
        key: 'VOICE BODY',
        title: 'Voice / Body',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512961',
        style: navigationItemStyles.thought,
        soundURL: 'sounds/universe-loop-3.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .4,
        pathSpeed: .00005,
        pathOffset: 0,
    },
    {
        key: 'FEMINIST EARS THOUGHT',
        title: 'Feminist Ears',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512964',
        style: navigationItemStyles.thought,
        soundURL: 'sounds/universe-loop-9.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .4,
        pathSpeed: .00005,
        pathOffset: Math.PI / 2,
    },
    {
        key: 'SWEET SPOT THOUGHT',
        title: 'Sweet Spot',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512971',
        style: navigationItemStyles.thought,
        soundURL: 'sounds/universe-loop-10.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .4,
        pathSpeed: .00005,
        pathOffset: Math.PI,
    },
    {
        key: 'SOUND CONTROL',
        title: 'Sound Control',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3662652',
        style: navigationItemStyles.thought,
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .4,
        pathSpeed: .00005,
        pathOffset: 3 * Math.PI / 2,
    },

    // Intro
    {
        key: 'INTRO',
        title: 'Intro',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512978',
        style: navigationItemStyles.intro,
        soundURL: 'sounds/universe-loop-11.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_RIGHT,
        pathScale: .5,
        pathSpeed: .00012,
        pathOffset: 4 * Math.PI / 3,
    }
]