const navigationItemProps = [
    {
        key: 'PERFORMANCE',
        title: 'PERFORMANCE',
        type: 'group',
        style: navigationItemStyles.Output,
        soundURL: 'sounds/test-tone-6.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .125,
        pathSpeed: .00005,
        pathOffset: 0,
        subItems: [
            'PERFORMANCE 1',
            'PERFORMANCE 2',
            'PERFORMANCE 3',
            'PERFORMANCE 4',
            'PERFORMANCE 5',
            'PERFORMANCE 6',
            'PERFORMANCE 7'
        ]
    },
    {
        key: 'PERFORMANCE 1',
        title: 'PERFORMANCE 1',
        type: 'subItem',
        link: '',
        style: navigationItemStyles.Output,
        imageURL: 'images/performance-preview.png',
        alwaysShowImage: true,
        pointRadius: 60,
        soundRadius: 150,
        path: PATHS.ROSE_LEFT,
        pathScale: 0,
        pathSpeed: .00005,
        pathOffset: 0,
    },
    {
        key: 'PERFORMANCE 2',
        title: 'PERFORMANCE 2',
        type: 'subItem',
        link: '',
        style: navigationItemStyles.Output,
        imageURL: 'images/performance-preview.png',
        alwaysShowImage: true,
        pointRadius: 40,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .2,
        pathSpeed: .00005,
        pathOffset: 0,
    },
    {
        key: 'PERFORMANCE 3',
        title: 'PERFORMANCE 3',
        type: 'subItem',
        link: '',
        style: navigationItemStyles.Output,
        imageURL: 'images/performance-preview.png',
        alwaysShowImage: true,
        pointRadius: 40,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .2,
        pathSpeed: .00005,
        pathOffset: Math.PI * 1 / 3,
    },
    {
        key: 'PERFORMANCE 4',
        title: 'PERFORMANCE 4',
        type: 'subItem',
        link: '',
        style: navigationItemStyles.Output,
        imageURL: 'images/performance-preview.png',
        alwaysShowImage: true,
        pointRadius: 40,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .2,
        pathSpeed: .00005,
        pathOffset: Math.PI * 2 / 3,
    },
    {
        key: 'PERFORMANCE 5',
        title: 'PERFORMANCE 5',
        type: 'subItem',
        link: '',
        style: navigationItemStyles.Output,
        imageURL: 'images/performance-preview.png',
        alwaysShowImage: true,
        pointRadius: 40,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .2,
        pathSpeed: .00005,
        pathOffset: Math.PI * 3 / 3,
    },
    {
        key: 'PERFORMANCE 6',
        title: 'PERFORMANCE 6',
        type: 'subItem',
        link: '',
        style: navigationItemStyles.Output,
        imageURL: 'images/performance-preview.png',
        alwaysShowImage: true,
        pointRadius: 40,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .2,
        pathSpeed: .00005,
        pathOffset: Math.PI * 4 / 3,
    },
    {
        key: 'PERFORMANCE 7',
        title: 'PERFORMANCE 7',
        type: 'subItem',
        link: '',
        style: navigationItemStyles.Output,
        imageURL: 'images/performance-preview.png',
        alwaysShowImage: true,
        pointRadius: 40,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .2,
        pathSpeed: .00005,
        pathOffset: Math.PI * 5 / 3,
    },
    {
        key: 'SPATIAL STRATEGIES',
        title: 'SPATIAL STRATEGIES',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3539951',
        style: navigationItemStyles.Output,
        soundURL: 'sounds/test-tone-5.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .125,
        pathSpeed: .00005,
        pathOffset: Math.PI / 2,
    },
    {
        key: 'CHAOS PENDULUM',
        title: 'CHAOS PENDULUM',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3539328',
        style: navigationItemStyles.Output,
        soundURL: 'sounds/test-tone-2.mp3',
        imageURL: 'images/chaos-pendulum-preview.png',
        alwaysShowImage: true,
        pointRadius: 40,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .125,
        pathSpeed: .00005,
        pathOffset: 0,
    },
    {
        key: `SPACE HALO (HALO D'ESPACE)`,
        title: `SPACE HALO (HALO D'ESPACE)`,
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3539325',
        style: navigationItemStyles.Output,
        soundURL: 'sounds/test-tone-1.mp3',
        imageURL: 'images/space-halo-preview.png',
        alwaysShowImage: true,
        pointRadius: 40,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .125,
        pathSpeed: .00005,
        pathOffset: Math.PI * 2 / 3,
    },
    {
        key: 'BAGUA INTERFACE',
        title: 'BAGUA',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3539322',
        style: navigationItemStyles.Output,
        soundURL: 'sounds/test-tone-3.mp3',
        imageURL: 'images/bagua-preview.png',
        alwaysShowImage: true,
        pointRadius: 40,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .125,
        pathSpeed: .00005,
        pathOffset: Math.PI * 4 / 3,
    },
    {
        key: 'MULTI VOICING SPATIAL SONGS',
        title: 'MULTI VOICING SPATIAL SONGS',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512955',
        style: navigationItemStyles.Output,
        soundURL: 'sounds/test-tone-7.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathOffset: Math.PI,
        pathScale: .125,
        pathSpeed: .00005,
        pathOffset: Math.PI * 1.5,
    },
    {
        key: 'GOING SPATIAL',
        title: 'GOING SPATIAL',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512949',
        style: navigationItemStyles.Process,
        soundURL: 'sounds/test-tone-4.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .4,
        pathSpeed: .00007,
        pathOffset: 0,
    },
    {
        key: 'INTERFACES',
        title: 'INTERFACES',
        type: 'group',
        style: navigationItemStyles.Process,
        soundURL: 'sounds/test-tone-10.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .4,
        pathSpeed: .00007,
        pathOffset: Math.PI * 2 / 3,
        subItems: ['CHAOS PENDULUM', `SPACE HALO (HALO D'ESPACE)`, 'BAGUA INTERFACE']
    },
    {
        key: 'SPATIAL SONGWRITING EXPERIMENTS',
        title: 'SPATIAL SONGWRITING EXPERIMENTS',
        type: 'group',
        style: navigationItemStyles.Process,
        soundURL: 'sounds/test-tone-6.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .4,
        pathSpeed: .00007,
        pathOffset: Math.PI * 4 / 3,
        subItems: ['GHOSTLY VOICE', 'BAGUA EXPERIMENT', 'SWEET SPOT EXPERIMENT', 'LISSAJOUS', '12 BUTTERFLIES']
    },
    {
        key: 'GHOSTLY VOICE',
        title: 'GHOSTLY VOICE',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3512958',
        style: navigationItemStyles.Process,
        soundURL: 'sounds/test-tone-6.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: 0,
        pathSpeed: 0,
        pathOffset: 0,
    },
    {
        key: 'BAGUA EXPERIMENT',
        title: 'BAGUA',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3512958',
        style: navigationItemStyles.Process,
        soundURL: 'sounds/test-tone-6.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .2,
        pathSpeed: .00007,
        pathOffset: 0,
    },
    {
        key: 'SWEET SPOT EXPERIMENT',
        title: 'SWEET SPOT',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3512958',
        style: navigationItemStyles.Process,
        soundURL: 'sounds/test-tone-6.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .2,
        pathSpeed: .00007,
        pathOffset: Math.PI / 2,
    },
    {
        key: 'LISSAJOUS',
        title: 'LISSAJOUS',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3512958',
        style: navigationItemStyles.Process,
        soundURL: 'sounds/test-tone-6.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .2,
        pathSpeed: .00007,
        pathOffset: Math.PI,
    },
    {
        key: '12 BUTTERFLIES',
        title: '12 BUTTERFLIES',
        type: 'subItem',
        link: 'https://www.researchcatalogue.net/view/3512750/3512958',
        style: navigationItemStyles.Process,
        soundURL: 'sounds/test-tone-6.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .2,
        pathSpeed: .00007,
        pathOffset: Math.PI * 3 / 2,
    },
    {
        key: 'SWEET SPOT THOUGHT',
        title: 'SWEET SPOT',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512964',
        style: navigationItemStyles.Thought,
        soundURL: 'sounds/test-tone-9.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .3,
        pathSpeed: .00002,
        pathOffset: Math.PI / 2,
    },
    {
        key: 'AGENCY',
        title: 'AGENCY',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512967',
        style: navigationItemStyles.Thought,
        soundURL: 'sounds/test-tone-4.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .375,
        pathSpeed: .0001,
        pathOffset: -Math.PI / 2,
    },
    {
        key: 'SONIC / SPACE',
        title: 'SONIC / SPACE',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512971',
        style: navigationItemStyles.Thought,
        soundURL: 'sounds/test-tone-3.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .25,
        pathSpeed: .00007,
        pathOffset: Math.PI,
    },
    {
        key: 'TECHNO VOICE',
        title: 'TECHNO VOICE',
        type: 'link',
        link: 'https://www.researchcatalogue.net/view/3512750/3512961',
        style: navigationItemStyles.Thought,
        soundURL: 'sounds/test-tone-2.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_LEFT,
        pathScale: .18,
        pathSpeed: .00007,
        pathOffset: 0,
    },
    {
        key: 'INSPIRATION',
        title: 'INSPIRATION',
        type: 'group',
        style: navigationItemStyles.Inspiration,
        soundURL: 'sounds/test-tone-1.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ORBIT_RIGHT,
        pathScale: .4,
        pathSpeed: .00002,
        pathOffset: 0,
        subItems: ['INSPIRATION 1', 'INSPIRATION 2', 'INSPIRATION 3']
    },
    {
        key: 'INSPIRATION 1',
        title: 'INSPIRATION 1',
        type: 'subItem',
        style: navigationItemStyles.Inspiration,
        link: '',
        soundURL: 'sounds/test-tone-1.mp3',
        pointRadius: 10,
        soundRadius: 100,
        path: PATHS.ROSE_LEFT,
        pathScale: .2,
        pathSpeed: .00007,
        pathOffset: 0,
    },
    {
        key: 'INSPIRATION 2',
        title: 'INSPIRATION 2',
        type: 'subItem',
        style: navigationItemStyles.Inspiration,
        link: '',
        soundURL: 'sounds/test-tone-1.mp3',
        path: PATHS.ROSE_LEFT,
        pointRadius: 10,
        soundRadius: 100,
        pathScale: .2,
        pathSpeed: .00007,
        pathOffset: Math.PI * 2 / 3,
    },
    {
        key: 'INSPIRATION 3',
        title: 'INSPIRATION 3',
        type: 'subItem',
        style: navigationItemStyles.Inspiration,
        link: '',
        soundURL: 'sounds/test-tone-1.mp3',
        path: PATHS.ROSE_LEFT,
        pointRadius: 10,
        soundRadius: 100,
        pathScale: .2,
        pathSpeed: .00007,
        pathOffset: Math.PI * 4 / 3,
    },
]