const pageItems = [
    {
        title: 'Performance',
        link: 'https://www.researchcatalogue.net/view/3512750/3512949',
        style: itemStyles.Output,
        soundURL: 'sounds/test-tone-6.mp3',
        imageUrl: 'images/test.png',
        x: window.innerWidth / 2,
        y: window.innerHeight / 2,
        pointRadius: 10,
        soundRadius: 100,
        path: paths.orbitRight,
        pathScale: 60,
        pathSpeed: .00005,
        pathOffset: 0,
    },
    {
        title: 'Spatial Strategies Prompts',
        link: '/spatial-strategies.html',
        style: itemStyles.Output,
        soundURL: 'sounds/test-tone-5.mp3',
        x: window.innerWidth / 2,
        y: window.innerHeight / 2,
        pointRadius: 10,
        soundRadius: 100,
        path: paths.orbitRight,
        pathScale: 60,
        pathSpeed: .00005,
        pathOffset: Math.PI / 2,
    },
    {
        title: 'Interfaces',
        link: 'https://www.researchcatalogue.net/view/3512750/3512958',
        style: itemStyles.Output,
        soundURL: 'sounds/test-tone-8.mp3',
        x: window.innerWidth / 2,
        y: window.innerHeight / 2,
        pointRadius: 10,
        soundRadius: 100,
        path: paths.orbitRight,
        pathScale: 60,
        pathSpeed: .00005,
        pathOffset: Math.PI,
    },
    {
        title: 'Sound Scores Publication',
        link: 'https://www.researchcatalogue.net/view/3512750/3512955',
        style: itemStyles.Output,
        soundURL: 'sounds/test-tone-7.mp3',
        x: window.innerWidth / 2,
        y: window.innerHeight / 2,
        pointRadius: 10,
        soundRadius: 100,
        path: paths.orbitRight,
        pathOffset: Math.PI,
        pathScale: 60,
        pathSpeed: .00005,
        pathOffset: Math.PI * 1.5,
    },
    {
        title: 'Process',
        link: 'https://www.researchcatalogue.net/view/3512750/3512975',
        style: itemStyles.Process,
        soundURL: 'sounds/test-tone-10.mp3',
        x: window.innerWidth / 2,
        y: window.innerHeight / 2,
        pointRadius: 10,
        soundRadius: 100,
        path: paths.roseLeft,
        pathScale: 250,
        pathSpeed: .0001,
        pathOffset: Math.PI / 2,
    },
    {
        title: 'Sweet Spot',
        link: 'https://www.researchcatalogue.net/view/3512750/3512964',
        style: itemStyles.Thought,
        soundURL: 'sounds/test-tone-9.mp3',
        x: window.innerWidth / 2,
        y: window.innerHeight / 2,
        pointRadius: 10,
        soundRadius: 100,
        path: paths.orbitLeft,
        pathScale: 200,
        pathSpeed: .00002,
        pathOffset: Math.PI / 2,
    },
    {
        title: 'Agency',
        link: 'https://www.researchcatalogue.net/view/3512750/3512967',
        style: itemStyles.Thought,
        soundURL: 'sounds/test-tone-4.mp3',
        x: window.innerWidth / 2,
        y: window.innerHeight / 2,
        pointRadius: 10,
        soundRadius: 100,
        path: paths.orbitRight,
        pathScale: 250,
        pathSpeed: .0001,
        pathOffset: -Math.PI / 2,
    },
    {
        title: 'Sonic / Space',
        link: 'https://www.researchcatalogue.net/view/3512750/3512971',
        style: itemStyles.Thought,
        soundURL: 'sounds/test-tone-3.mp3',
        x: window.innerWidth / 2,
        y: window.innerHeight / 2,
        pointRadius: 10,
        soundRadius: 100,
        path: paths.orbitLeft,
        pathScale: 150,
        pathSpeed: .00007,
        pathOffset: Math.PI,
    },
    {
        title: 'Techno Voice',
        link: 'https://www.researchcatalogue.net/view/3512750/3512961',
        style: itemStyles.Thought,
        soundURL: 'sounds/test-tone-2.mp3',
        x: window.innerWidth / 2,
        y: window.innerHeight / 2,
        pointRadius: 10,
        soundRadius: 100,
        path: paths.orbitLeft,
        pathScale: 100,
        pathSpeed: .00007,
        pathOffset: 0,
    },
    {
        title: 'Inspiration',
        link: 'https://www.researchcatalogue.net/view/3512750/3512978',
        style: itemStyles.Inspiration,
        soundURL: 'sounds/test-tone-1.mp3',
        x: window.innerWidth / 2,
        y: window.innerHeight / 2,
        pointRadius: 10,
        soundRadius: 100,
        path: paths.orbitRight,
        pathScale: 325,
        pathSpeed: .00002,
        pathOffset: 0,
    },
]

const pageItemGroups = {
    Process: {
        title: 'Process',
        style: itemStyles.Process,
        soundURL: 'sounds/test-tone-6.mp3',
        x: window.innerWidth / 2,
        y: window.innerHeight / 2,
        pointRadius: 10,
        soundRadius: 100,
        path: paths.orbitRight,
        pathScale: 60,
        pathSpeed: .00005,
        pathOffset: 0,
        subItems: [
            pageItems.HardwareSoftware,
            pageItems.SpatialSongwritingExperiments,
            pageItems.Interfaces,
            pageItems.GoingSpatial,
        ]
    },
}